spring.application.name=bookmarks-manager
spring.data.mongodb.uri=mongodb+srv://mongoApplication_db_user:ydCo7NYxzfwNqhEf@dbcluster101.qeo94jc.mongodb.net/testSchema?appName=DBCluster101
spring.data.mongodb.database=testSchema
server.error.include-message=always
server.error.include-binding-errors=always
#
server.port=8080

# jpa
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true


#removing csrf by calling it strict
server.servlet.session.cookie.same-site=strict


#smtp
spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=api
spring.mail.password=c6a3fd1418dfac89fbd867adc8e4b31d
# Standard Spring Mail Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true